### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by KaidenTheCEO** [ibra-akv/qb-cocaine#1]
hello ive started the resource and followed every step but the script isnt working

**Comment by 0xIbra** [comment]
Hi @KaidenTheCEO,

Do you confirm that your server is running with QBCore ? This script only works on QBCore framework.

This script is dependent on **qb-core** and **qb-inventory** resources and so it must start after those 2 resources have started.

Have you checked the logs, does it output any errors ?

**Comment by ghost** [comment]
Mine works

**Comment by KaidenTheCEO** [comment]
Yes it is running QBCore. And yes, qb inventory is installed. No errors.

**Comment by ghost** [comment]
mine works fine so im wondering i even added more drugs to it using this as base

**Comment by 0xIbra** [comment]
@KaidenTheCEO 
Without more insight into your code i cannot help.
If you really need help, i can take a look at it.
If that's something you wanna do add me on discord: **Ibra#5374**
